#include <mregex.hpp>

namespace meta::tests
{
    namespace
    {
        template<static_string Pattern>
        inline constexpr bool accepted = parser<Pattern>::accepted;
    }

    // Test valid inputs
    static_assert(accepted<R"()">);
    static_assert(accepted<R"(a)">);
    static_assert(accepted<R"(\\)">);
    static_assert(accepted<R"(\\a)">);
    static_assert(accepted<R"(\\D)">);
    static_assert(accepted<R"(abcdefg)">);
    static_assert(accepted<R"((c))">);
    static_assert(accepted<R"((c)\1)">);
    static_assert(accepted<R"(c?)">);
    static_assert(accepted<R"(c*)">);
    static_assert(accepted<R"(c+)">);
    static_assert(accepted<R"(c??)">);
    static_assert(accepted<R"(c*?)">);
    static_assert(accepted<R"(c+?)">);
    static_assert(accepted<R"(c{2})">);
    static_assert(accepted<R"(c{2}?)">);
    static_assert(accepted<R"(c{})">);
    static_assert(accepted<R"(c{}?)">);
    static_assert(accepted<R"(c{)">);
    static_assert(accepted<R"(c{?)">);
    static_assert(accepted<R"(c{?})">);
    static_assert(accepted<R"(c{?}?)">);
    static_assert(accepted<R"(c{,0})">);
    static_assert(accepted<R"(c{,0}?)">);
    static_assert(accepted<R"(c{*})">);
    static_assert(accepted<R"(c{+})">);
    static_assert(accepted<R"(c{|})">);
    static_assert(accepted<R"(c{x})">);
    static_assert(accepted<R"(c{0})">);
    static_assert(accepted<R"(c{123})">);
    static_assert(accepted<R"(c{1,23})">);
    static_assert(accepted<R"(c{12,})">);
    static_assert(accepted<R"(c{0,123})">);
    static_assert(accepted<R"(c{0,123}?)">);
    static_assert(accepted<R"(c{1,2})">);
    static_assert(accepted<R"(c{,})">);
    static_assert(accepted<R"(c{ 0, 123})">);
    static_assert(accepted<R"(c\{123})">);
    static_assert(accepted<R"(c\{)">);
    static_assert(accepted<R"(^c+)">);
    static_assert(accepted<R"(^c+$)">);
    static_assert(accepted<R"(one|two)">);
    static_assert(accepted<R"((one|two)?)">);
    static_assert(accepted<R"((one|two)*)">);
    static_assert(accepted<R"((one|two)+)">);
    static_assert(accepted<R"(one+|two)">);
    static_assert(accepted<R"((one|two?)?)">);
    static_assert(accepted<R"((one*|two)*)">);
    static_assert(accepted<R"((one|two|three?)?)">);
    static_assert(accepted<R"((one+|two|three)*)">);
    static_assert(accepted<R"((one|two+|three)+)">);
    static_assert(accepted<R"((\(+)*)">);
    static_assert(accepted<R"((\++?)*)">);
    static_assert(accepted<R"((\?+)?)">);
    static_assert(accepted<R"((\?+?)?)">);
    static_assert(accepted<R"((\|+\))?)">);
    static_assert(accepted<R"(x(?:x))">);
    static_assert(accepted<R"((?:x)x)">);
    static_assert(accepted<R"((?:x)?)">);
    static_assert(accepted<R"((?:x)+)">);
    static_assert(accepted<R"(x+(?:x)?y*)">);
    static_assert(accepted<R"((?:ab|cd)?)">);
    static_assert(accepted<R"((?:abcd)|xy)">);
    static_assert(accepted<R"((?:ab|cd)|xy)">);
    static_assert(accepted<R"((?:(abc){4}))">);
    static_assert(accepted<R"((?:(?:abc)))">);
    static_assert(accepted<R"(xyz(?=a)abc)">);
    static_assert(accepted<R"(xyz(?!a)abc)">);
    static_assert(accepted<R"(xyz(?<=abc)abc)">);
    static_assert(accepted<R"(xyz(?<!abc)abc)">);
    static_assert(accepted<R"(xyz(?<=a)abc)">);
    static_assert(accepted<R"(xyz(?<!a)abc)">);
    static_assert(accepted<R"(12(ab(?:cd)ef)\1gh)">);
    static_assert(accepted<R"((?:(((?:abd))+)x?)|(?:xyz)+)">);
    static_assert(accepted<R"(x*(x?(abc+(?:xyz)?)+x)*x)">);
    static_assert(accepted<R"(x*(x?(abc+(?:xyz)?)+x)*x\1+\2?)">);
    static_assert(accepted<R"(x*?(x?(abc+?(?:xyz)?)+x)*x\1+?\2??)">);
    static_assert(accepted<R"(x\*\(x\?(abc\+(?:xyz)\?)\+x\)\*x)">);
    static_assert(accepted<R"([a])">);
    static_assert(accepted<R"([a][b])">);
    static_assert(accepted<R"([])">);
    static_assert(accepted<R"([^])">);
    static_assert(accepted<R"([a]{12}[])">);
    static_assert(accepted<R"([][b])">);
    static_assert(accepted<R"(^[a]$)">);
    static_assert(accepted<R"(])">);
    static_assert(accepted<R"([]])">);
    static_assert(accepted<R"([^a])">);
    static_assert(accepted<R"([^-a])">);
    static_assert(accepted<R"([-a])">);
    static_assert(accepted<R"([a-z])">);
    static_assert(accepted<R"([]-z])">);
    static_assert(accepted<R"([^a-z])">);
    static_assert(accepted<R"(^[^a-z]$)">);
    static_assert(accepted<R"([^-a-z])">);
    static_assert(accepted<R"([- -[])">);
    static_assert(accepted<R"([a-\\w])">);
    static_assert(accepted<R"(f?[a-zA-Z]?a?)">);
    static_assert(accepted<R"(f?[a-z-]?a?)">);
    static_assert(accepted<R"(f?[a-z-A]?a?)">);
    static_assert(accepted<R"(f??[a-z-A]??a?)">);
    static_assert(accepted<R"(f*[a-zA-Z]*a?)">);
    static_assert(accepted<R"(f+[a-zA-Z]+a+)">);
    static_assert(accepted<R"(f?[a-zA-Z]?a?[xyzt\w0-9]+d?)">);
    static_assert(accepted<R"(ab|cd|[a-zA-Z]|ab{3}|ac)">);
    static_assert(accepted<R"(ab|(cd|[a-zA-Z]|ab)|ac)">);
    static_assert(accepted<R"(^(ab|(cd|[a-zA-Z]|ab)|ac)$)">);
    static_assert(accepted<R"(((a|\\a)|(d|\\d))?)">);
    static_assert(accepted<R"(((a|\\a+)|(d?|\\d))*)">);
    static_assert(accepted<R"(((a|\\a)|(0|1|2|3))?)">);
    static_assert(accepted<R"((((a|\\a)|(0|1|2|3))?)*x?y+abcd|efgh((x|z)?t)+)">);
    static_assert(accepted<R"(abc(?<test>.[a-d]+)*cd)">);
    static_assert(accepted<R"(abc(?<te2_3>.[a-d]+)+cd)">);
    static_assert(accepted<R"(abc(?<lvl1>.[a-d]+(?<lvl2>x+y*))+cd)">);
    static_assert(accepted<R"(abc(?<____>.[a-d]+(?<_1232>x+y*)+){2,3}cd)">);
    static_assert(accepted<R"(abc(?<____>.[a-d]+(?<_1232>x+y*)+){2,3}cd\k<_1232>+)">);
    static_assert(accepted<R"(abc(?<____>.[a-d]+(?<_1232>\k<____>{2}x+y*)+){2,3}cd)">);
    static_assert(accepted<R"((?<foo>.)\k<foo>\1)">);
    static_assert(accepted<R"((?<foo>.+?)\k<foo>*?\1)">);

    // Test invalid inputs
    static_assert(accepted<R"(()"> == false);
    static_assert(accepted<R"())"> == false);
    static_assert(accepted<R"(+)"> == false);
    static_assert(accepted<R"(?)"> == false);
    static_assert(accepted<R"(*)"> == false);
    static_assert(accepted<R"(|)"> == false);
    static_assert(accepted<R"(^?)"> == false);
    static_assert(accepted<R"(c{2x})"> == false);
    static_assert(accepted<R"(c{123)"> == false);
    static_assert(accepted<R"(c{123\})"> == false);
    static_assert(accepted<R"(c{123\})"> == false);
    static_assert(accepted<R"(c{1,2,3})"> == false);
    static_assert(accepted<R"(c{12,3)"> == false);
    static_assert(accepted<R"(c{0,123,})"> == false);
    static_assert(accepted<R"(c{0, 123})"> == false);
    static_assert(accepted<R"(c{0 ,123})"> == false);
    static_assert(accepted<R"(c{0,123 })"> == false);
    static_assert(accepted<R"(c{1\,2})"> == false);
    static_assert(accepted<R"($?)"> == false);
    static_assert(accepted<R"(^$+)"> == false);
    static_assert(accepted<R"(^$*)"> == false);
    static_assert(accepted<R"(^$*?)"> == false);
    static_assert(accepted<R"(^*$?)"> == false);
    static_assert(accepted<R"(^*$?)"> == false);
    static_assert(accepted<R"(^?$??)"> == false);
    static_assert(accepted<R"((+))"> == false);
    static_assert(accepted<R"((+))"> == false);
    static_assert(accepted<R"((?))"> == false);
    static_assert(accepted<R"((*))"> == false);
    static_assert(accepted<R"((())"> == false);
    static_assert(accepted<R"(()))"> == false);
    static_assert(accepted<R"((?:))"> == false);
    static_assert(accepted<R"(x(?))"> == false);
    static_assert(accepted<R"((?:xx)"> == false);
    static_assert(accepted<R"(?:x)?)"> == false);
    static_assert(accepted<R"((?:)+)"> == false);
    static_assert(accepted<R"(x+(?:?)*)"> == false);
    static_assert(accepted<R"((?:|x))"> == false);
    static_assert(accepted<R"((?:a)|)"> == false);
    static_assert(accepted<R"(|(?:ab))"> == false);
    static_assert(accepted<R"((?x))"> == false);
    static_assert(accepted<R"(xyz(?=)abc)"> == false);
    static_assert(accepted<R"(xyz(?!)abc)"> == false);
    static_assert(accepted<R"(xyz(?<abc)abc)"> == false);
    static_assert(accepted<R"(xyz(?<)abc)"> == false);
    static_assert(accepted<R"(xyz(?<a)abc)"> == false);
    static_assert(accepted<R"(xyz(?<<a)abc)"> == false);
    static_assert(accepted<R"((?:abc)"> == false);
    static_assert(accepted<R"((?:abc()))"> == false);
    static_assert(accepted<R"(xy?((?:abc)zt\)?)"> == false);
    static_assert(accepted<R"((|))"> == false);
    static_assert(accepted<R"(a|)"> == false);
    static_assert(accepted<R"(|a)"> == false);
    static_assert(accepted<R"(\)"> == false);
    static_assert(accepted<R"([\])"> == false);
    static_assert(accepted<R"([][)"> == false);
    static_assert(accepted<R"([)"> == false);
    static_assert(accepted<R"([a][)"> == false);
    static_assert(accepted<R"([^a-])"> == false);
    static_assert(accepted<R"(?[a-zA-Z]?a?)"> == false);
    static_assert(accepted<R"(ab||[a-zA-Z])"> == false);
    static_assert(accepted<R"(ab|(cd|[a-zA-Z]|)"> == false);
    static_assert(accepted<R"((a|))"> == false);
    static_assert(accepted<R"((a{|))"> == false);
    static_assert(accepted<R"((|a))"> == false);
    static_assert(accepted<R"((+|-))"> == false);
    static_assert(accepted<R"((Inner|a)+))"> == false);
    static_assert(accepted<R"(\((Inner|a)+))"> == false);
    static_assert(accepted<R"(((((((a))))))"> == false);
    static_assert(accepted<R"(((((((a)))))\))"> == false);
    static_assert(accepted<R"(f?[a-zA-]?a?)"> == false);
    static_assert(accepted<R"(f?[a--z-]?a?)"> == false);
    static_assert(accepted<R"(f?[a-z-A]?+)"> == false);
    static_assert(accepted<R"(f*[a-zA-Z*a?)"> == false);
    static_assert(accepted<R"(f**[a-zA-Z])"> == false);
    static_assert(accepted<R"(+[a-zA-Z]+a+)"> == false);
    static_assert(accepted<R"(ab|cd|[a-zA-Z]|ab{3|ac)"> == false);
    static_assert(accepted<R"(ab|(cd|[a-zA-Z]|ab\)|ac)"> == false);
    static_assert(accepted<R"(^(ab||(cd|[a-zA-Z]|ab)|ac)$)"> == false);
    static_assert(accepted<R"(((a|\\a)|\(d|\\d))?)"> == false);
    static_assert(accepted<R"(((a|\\a++)|(d?|\\d))*)"> == false);
    static_assert(accepted<R"(((a|\\a)|(0|1|?2|3))?)"> == false);
    static_assert(accepted<R"((((|\\a)|(0|1|2|3))?)*x?y+abcd|efgh((x|z)?t)+)"> == false);
    static_assert(accepted<R"((?<1name>xyz))"> == false);
    static_assert(accepted<R"((?<namexyz))"> == false);
    static_assert(accepted<R"((?<name >xyz))"> == false);
    static_assert(accepted<R"((?< name>xyz))"> == false);
    static_assert(accepted<R"((?<+name>xyz))"> == false);
    static_assert(accepted<R"(\k<+name>)"> == false);
    static_assert(accepted<R"(\k<name)"> == false);
    static_assert(accepted<R"(\kname>)"> == false);
    static_assert(accepted<R"(\k<1name>)"> == false);
    static_assert(accepted<R"(\k<name>*+)"> == false);
    static_assert(accepted<R"(\k<)"> == false);
    static_assert(accepted<R"(\k)"> == false);
}