language: cpp
dist: focal
os: linux
jobs:
  include:
    - compiler: gcc
      env: CXX_COMPILER=g++-11
      addons:
        apt:
          packages:
            - g++-11

    - compiler: clang
      env: CXX_COMPILER=clang++-12
      addons:
        apt:
          packages:
            - clang-12
            - g++-11
          sources:
            - sourceline: 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
  - sudo apt install -y g++-11
  - sudo apt install cmake
  - cmake --version
  - export CXX=${CXX_COMPILER}
  - $CXX --version

script:
  - cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cmake --build build --target all --config Release -- -j4