language: cpp
dist: focal
os: linux
jobs:
  include:
    - compiler: gcc
      env: CXX_COMPILER=g++-10
      addons:
        apt:
          packages:
            - g++-10

    - compiler: clang
      env: CXX_COMPILER=clang++-12
      addons:
        apt:
          packages:
            - clang-12
            - g++-10
          sources:
            - sourceline: 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

before_install:
  - sudo apt-get update
  - sudo apt install cmake
  - cmake --version

install:
  - export CXX=${CXX_COMPILER}
  - $CXX --version

script:
  - mkdir build && cd build
  - cmake ..
  - make