name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc-11, gcc-13, llvm-14, llvm-16]
        include:
          - compiler: gcc-11
            os: ubuntu-22.04
            CXX: g++-11

          - compiler: gcc-13
            os: ubuntu-22.04
            CXX: g++-13

          - compiler: llvm-14
            os: ubuntu-22.04
            CXX: clang++-14

          - compiler: llvm-16
            os: ubuntu-22.04
            CXX: clang++-16

    runs-on: ${{ matrix.os }}
    env:
      CXX: ${{ matrix.CXX }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set-up toolchain
        uses: aminya/setup-cpp@v1.8.0
        with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: false
          cmake: true
          ninja: false
          vcpkg: false

      - name: CMake generate Makefiles
        run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: CMake build
        run: cmake --build build --target all --config Release -- -j$(nproc)
